[book]
authors = ["borbalp"]
language = "en"
multilingual = false
src = "src"
title = "GCP Exam Materials"

[output.html]
additional-css = ["src/book.css"]
site-url = "/gcp-prep/"
git-repository-url = "https://github.com/borbalp/gcp-prep"